### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rnestler**
- [x] Upgrade evn_logger
- [x] Upgrade docopt
- [x] Upgrade spaceapi-server

### CODE REVIEW

**Comment by rnestler** [comment]
Updating to docopt 0.8 was totally worth it! Since it uses serde we can get rid of our new-type wrapping of Ip4Addr to implement custom deserialization!

Slightly related: We do we only allow IP4 addresses? Shouldn't we also allow host names (like localhost) and IP6 addresses?

**Comment by dbrgn** [comment]
> Updating to docopt 0.8 was totally worth it! Since it uses serde we can get rid of our new-type wrapping of Ip4Addr to implement custom deserialization!

Awesome!

> Slightly related: We do we only allow IP4 addresses? Shouldn't we also allow host names (like localhost) and IP6 addresses?

You're right. Can we somehow allow any value that implements `ToSocketAddr`?

**Comment by rnestler** [comment]
> You're right. Can we somehow allow any value that implements ToSocketAddr?

The easiest thing for now would be to use https://doc.rust-lang.org/nightly/std/net/enum.IpAddr.html. This would at least allow IPv4 and IPv6 addresses.

**Comment by dbrgn** [comment]
Agree!

**Comment by rnestler** [comment]
@dbrgn Ready for review.

**Pull request merged**
