### PR TITLE
Server update

### PR DESCRIPTION
**Pull request by dbrgn**
- Update spaceapi-server to 0.2.0
- Upgrade code accordingly
- Bump version to 0.2.0

### CODE REVIEW

**Comment by rnestler** [comment]
ah mabe look at #85

**Comment by dbrgn** [comment]
Aaah :)

Maybe we can combine the two changesets? E.g. add `unwrap_or_else` and the separate redis variable to your commit?

**Comment by rnestler** [comment]
Yes that would be nice. I will try to put the error handling commit on top of #85

**Comment by dbrgn** [comment]
Does expect show the inner error message too?

**Comment by dbrgn** [comment]
@rnestler what's the status on this? I'm confused :)

**Comment by rnestler** [comment]
@dbrgn I'm sorry haven't really looked into it for some time :cry: Will take a look at it this week :smiley:

**Comment by dbrgn** [comment]
@rnestler o rly? :laughing:

**Comment by rnestler** [comment]
@dbrgn So it was more like 3 weeks but I think #92 should now be in a mergable state :smiley:

**Comment by rnestler** [comment]
With the merge of #85 we can close this.

**Pull request closed without merging**
