### PR TITLE
Update to spaceapi-server 0.2

### PR DESCRIPTION
**Pull request by rnestler**
It should still work the same as before ;)

### CODE REVIEW

**Comment by dbrgn** [comment]
> for testing only

I'm working on integration tests, so that we can test this in a proper test, instead of having to adjust the `status` repo each time.

**Comment by dns2utf8** [comment]
Is this still on track or did we implement something similar already?

**Comment by rnestler** [comment]
I think this is still active. We should create a new release of spaceapi-server-rs

**Comment by dbrgn** [comment]
Yep :)

When we can merge https://github.com/coredump-ch/spaceapi-server-rs/pull/29, we can close https://github.com/coredump-ch/spaceapi-server-rs/issues/19 which would make the milestone https://github.com/coredump-ch/spaceapi-server-rs/milestones/Version%200.2.0 almost complete.

**Comment by rnestler** [comment]
@dbrgn Care to review? Will probably squash it.

**Comment by dbrgn** [comment]
+1 for the `expect` calls :)

Good to squash from me.

**Pull request merged**
