### PR TITLE
Docker: Use rust image to build and debian-slim to run

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by dbrgn** [comment]
True. The Jessie image was a bit smaller:

```
coredump/status                   rust                7dca49fed7a3        12 seconds ago      1.76GB
coredump/status                   jessie              fb6a2e0950fd        2 minutes ago       1.03GB
```

However, we can use the Rust image as an intermediate step only, and then copy the artifact into a `debian:stable-slim` container.

```
coredump/status                   builder             7fd71a3d7694        6 seconds ago       61.4MB
```

(We could also build using musl and copy the target to an alpine image, but I'm not sure if it's worth the hassle.)

Here's the diff:

```diff
diff --git a/Dockerfile b/Dockerfile
index 0667c21..6db2f8e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,17 +1,15 @@
-FROM rust:1.34
-MAINTAINER Danilo Bargen <mail@dbrgn.ch>
-
 # Build spaceapi
+FROM rust:1 as builder
 WORKDIR /source
 COPY . /source
 RUN cargo build --release && \
     cp target/release/coredump-status /usr/local/bin/coredump-status && \
     cd / && rm -rf /source
 
-# Set runtime related environment variables
+# Create actual container
+FROM debian:stable-slim
+COPY --from=builder /usr/local/bin/coredump-status /usr/local/bin/
 ENV RUST_LOG=warn,spaceapi=info,spaceapi_server=info \
     REDIS_HOST=spaceapi-redis
-
-# Entry point
 EXPOSE 3000
 CMD ["/usr/local/bin/coredump-status", "-i", "0.0.0.0", "-p", "3000"]
```

**Comment by rnestler** [comment]
I applied your idea. Seems to work very nicely :slightly_smiling_face: A few things

When I run the container I can't stop it with Ctrl-C:
```
% docker run -it coredump-status
Starting HTTP server on:
	http://0.0.0.0:3000
^C^C^C^C
```
Do you know the reasons?

Also should we use `ENTRYPOINT` instead of only `CMD`?

**Comment by rnestler** [comment]
> When I run the container I can't stop it with Ctrl-C:

Found it: https://stackoverflow.com/questions/37515686/stop-a-running-docker-container-by-sending-sigterm. We should handle the SIGTERM directly. Maybe use https://crates.io/crates/ctrlc? But that is for a separate PR.

**Comment by rnestler** [comment]
@dbrgn good to merge?

**Pull request merged**
