### PR TITLE
Rust compiler

### PR DESCRIPTION
**Pull request by dns2utf8**
Update compiler inside Dockerfile

### CODE REVIEW

**Comment by dns2utf8** [comment]
Updated for scheduled for stable release on May 26, 2016.

**Comment by dbrgn** [comment]
Do we get any advantage from using the latest compiler, even if we don't use newer features?

**Comment by rnestler** [comment]
I would use the lowest supported version of the rust compiler to verify that it still works.

**Comment by dns2utf8** [comment]
I would update it every now and then to see if it still works with the current version in case we would like to use newer features in the future.

**Comment by dbrgn** [comment]
> I would suggest to use the lowest supported version of the rust compiler to verify that it still works.

In theory that's the domain of the test suite though :) But you're right, we could miss something.

> I would update it every now and then to see if it still works with the current version in case we would like to use newer features in the future.

Rust should be forward compatible. If we want to use newer features, then we should update the minimal required version in the README.

**Pull request merged**
