### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by dbrgn**
- Disable IRC notifications.
- Disable builds on beta and nightly. All we care about is stable.

### CODE REVIEW

**Comment by rnestler** [comment]
> Disable builds on beta and nightly. All we care about is stable.

Is this true? Do you mean because it is specific to coredump so nobody else is gonna use it anyway?

**Comment by dbrgn** [comment]
Well, I'm pretty sure nobody is going to use the static version that include coredump information for another hackerspace 😉

**Comment by rnestler** [comment]
Do we need to test the Docker image as well in CI?

**Comment by dbrgn** [comment]
Yeah, we could actually do that. Do you want to create an issue for it?

**Pull request merged**
